#!/bin/bash
#SBATCH --job-name=degen-toy             # Job name
#SBATCH --nodes=1                       # Number of nodes
#SBATCH --ntasks=1                      # Number of tasks
#SBATCH --cpus-per-task=8              # CPUs per task
#SBATCH --time=00:20:00               # Time limit
#SBATCH --partition=shared             # Partition name
#SBATCH --account=phy240043            # Account name
#SBATCH --array=0-4
#SBATCH --output=/anvil/scratch/x-ctirapongpra/jobout/%x_%A_%a.out  # Output file
#SBATCH --error=/anvil/scratch/x-ctirapongpra/jobout/%x_%A_%a.out   # Error file

SCRIPTS=(
    "banana.py"
    "cubic.py"
    "pixel_mass.py"
    "scurve.py"
    "trig.py"
)

TOY_DIR="/anvil/scratch/x-ctirapongpra/degen_detector/reproduce/toy"
PROJECT_DIR="/home/x-ctirapongpra/scratch/degen_detector"

module load gcc/14.2.0

# Select script based on array task ID
SCRIPT=${SCRIPTS[$SLURM_ARRAY_TASK_ID]}

# Print job information
echo "Job ID: ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"
echo "Script: ${SCRIPT}"
echo "Node: $(hostname)"
echo "Start time: $(date)"

# Run the script
uv run --project ${PROJECT_DIR} python ${TOY_DIR}/${SCRIPT}

# Print completion info
echo "${SCRIPT} completed"
echo "End time: $(date)"
