#!/bin/bash
#SBATCH --job-name=degen-planck
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --partition=shared
#SBATCH --account=phy240043
#SBATCH --output=/anvil/scratch/x-ctirapongpra/jobout/%x_%j.out
#SBATCH --error=/anvil/scratch/x-ctirapongpra/jobout/%x_%j.out

SCIENCE_DIR="/anvil/scratch/x-ctirapongpra/degen_detector/reproduce/science"
PROJECT_DIR="/home/x-ctirapongpra/scratch/degen_detector"

module load gcc/14.2.0
module load julia/1.11.4
export PYTHON_JULIAPKG_EXE=$(which julia)

echo "Job ID: ${SLURM_JOB_ID}"
echo "Node: $(hostname)"
echo "Start time: $(date)"

uv run --project ${PROJECT_DIR} python ${SCIENCE_DIR}/planck/run.py "$@"

echo "Completed"
echo "End time: $(date)"
